resources:
  database_instances:
    webdemocracy_instance:
      name: webdemocracy-database-instance
      capacity: CU_2
  
  database_catalogs:
    webdemocracy_catalog:
      database_instance_name: ${resources.database_instances.webdemocracy_instance.name}
      database_name: "webdemocracy_db"
      name: webdemocracy_database_catalog
      create_database_if_not_exists: true

  synced_database_tables:
    eventhub_clean_ai:
      name: 'dad_open_data.news.eventhub_clean_ai_sync'
      database_instance_name: ${resources.database_instances.webdemocracy_instance.name}
      logical_database_name: ${resources.database_catalogs.webdemocracy_catalog.database_name}
      spec:
        source_table_full_name: 'dad_open_data.news.eventhub_clean_ai'
        scheduling_policy: CONTINUOUS
        primary_key_columns:
          - etl_rec_uuid
        create_database_objects_if_missing: true
        new_pipeline_spec:
          storage_catalog: 'dad_open_data'
          storage_schema: 'news'

    survey_ai:
      name: 'dad_open_data.news.survey_ai_sync'
      database_instance_name: ${resources.database_instances.webdemocracy_instance.name}
      logical_database_name: ${resources.database_catalogs.webdemocracy_catalog.database_name}
      spec:
        source_table_full_name: 'dad_open_data.news.survey_ai'
        scheduling_policy: CONTINUOUS
        primary_key_columns:
          - id
        create_database_objects_if_missing: true
        new_pipeline_spec:
          storage_catalog: 'dad_open_data'
          storage_schema: 'news'

    survey_options_ai:
      name: 'dad_open_data.news.survey_options_ai_sync'
      database_instance_name: ${resources.database_instances.webdemocracy_instance.name}
      logical_database_name: ${resources.database_catalogs.webdemocracy_catalog.database_name}
      spec:
        source_table_full_name: 'dad_open_data.news.survey_options_ai'
        scheduling_policy: CONTINUOUS
        primary_key_columns:
          - id
        create_database_objects_if_missing: true
        new_pipeline_spec:
          storage_catalog: 'dad_open_data'
          storage_schema: 'news'