resources:
  database_instances:
    webdemocracy_instance:
      name: webdemocracy-database-instance
      capacity: CU_2
  
  database_catalogs:
    webdemocracy_catalog:
      database_instance_name: ${resources.database_instances.webdemocracy_instance.name}
      database_name: "webdemocracy_db"
      name: webdemocracy_database_catalog
      create_database_if_not_exists: true

